version: '3.8'

services:
  scheduling-service:
    image: anisbenothman/scheduling-service:latest
    container_name: scheduling-service
    ports:
      - "8083:8083"
    environment:
      eureka.client.serviceUrl.defaultZone: "http://discover-service:8761/eureka/"
      SPRING.DATA.MONGODB.URI: "mongodb://mongodb:27017/scheduling-service"
      spring.data.mongodb.database: "scheduling-service"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: scheduling-service-group
      SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest

    depends_on:
      - mongodb
      - discover-service
      - gateway-service
    networks:
      - street-foot-network
  discover-service:
      image: anisbenothman/discover-service:latest
      container_name: discover-service
      ports:
        - "8761:8761"
      networks:
        - street-foot-network
  gateway-service:
      image: anisbenothman/gateway:latest
      container_name: gateway-service
      environment:
        eureka.client.serviceUrl.defaultZone: "http://discover-service:8761/eureka/"
      ports:
        - "8084:8084"
      networks:
        - street-foot-network
  mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "27017:27017"
      networks:
        - street-foot-network
      volumes:
          - mongo-data:/data/db
networks:
    street-foot-network:
        driver: bridge
        external: true
volumes:
    mongo-data:
