name: CI - Tournament Service

on:
  push:
    branches: [ "anis" ]
  pull_request:
    branches: [ "anis" ]

jobs:
  tournament-service:
    name: tournament-service Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build and install shared-library
        run: |
          cd shared-library
          mvn clean install
      - run: echo "shared library build successfully."
      
      - name: Compile
        run: mvn -f tournament-service/pom.xml clean compile -DskipTests

      - name: Build with Maven
        run: |
          mvn -B package --file tournament-service/pom.xml -DskipTests
            
      - name: SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_TOURNAMENT }}
        run: |
          mvn -f tournament-service/pom.xml -DskipTests \
          verify sonar:sonar \
          -Dsonar.projectKey=anisbenothman_StreetFoot_tournament-service \
          -Dsonar.login=${{ secrets.SONAR_TOKEN_TOURNAMENT }}

